name: currency_converter
description: "A new Flutter project."
publish_to: 'none' # Prevent accidental publication
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.0.15
  file_picker: ^5.2.7
  image_picker: ^1.1.2
  multi_select_flutter: ^4.0.0
  flutter_plugin_android_lifecycle: ^2.0.0
  provider: ^6.1.2
  #local
  flutter_localization: ^0.2.3
  intl: ^0.19.0
  
  geocoding: ^3.0.0
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  flutter_polyline_points: ^2.1.0
  permission_handler: ^11.3.1  
  location: ^7.0.1
  sensors_plus: ^6.1.0
  flutter_google_maps_webservices: ^1.1.1
#places
  google_places_for_flutter_3: ^1.0.4
  # geojson_vi: ^2.2.5
  geojson: ^1.0.0

  place_picker_google: ^0.0.13
  latlong2: ^0.8.0 

  flutter_typeahead: ^5.2.0
  rxdart: ^0.27.5

  #pie-char
  fl_chart: ^0.69.2

  fluttertoast: ^8.2.0

  #Firebase
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  # firebase_messaging: ^15.1.6
  # flutter_local_notifications: ^18.0.1
  # cloud_firestore: ^5.6.0
  flutter_secure_storage: ^9.2.2
  
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  #Payment
  flutter_stripe: ^11.3.0
  razorpay_flutter: ^1.3.7
  phonepe_payment_sdk: ^2.0.3
  crypto: ^3.0.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

#localization
  # flutter_gen: any
  # intl: any
  
  #testing api
  mocktail: ^1.0.4
  flutter_launcher_icons: "^0.14.1"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/liveIcon.png"

flutter:
  uses-material-design: true
  #add
  generate: true

  assets:
    - assets/images/
    - lib/l10n/
    

  