// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAldpQdfiRdY8sdoTTD02uw-m974xFzfrk',
    appId: '1:938443124208:web:18b06285de14bef8384135',
    messagingSenderId: '938443124208',
    projectId: 'fir-try-cff76',
    authDomain: 'fir-try-cff76.firebaseapp.com',
    storageBucket: 'fir-try-cff76.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmb3PNrVSSzE5_gh_t2XFEeZB3YDG5r0U',
    appId: '1:938443124208:android:9074bee30e1f0bc4384135',
    messagingSenderId: '938443124208',
    projectId: 'fir-try-cff76',
    storageBucket: 'fir-try-cff76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRmts0YwOhWdWEvTBkMiURXMcy_dRA8Wg',
    appId: '1:938443124208:ios:a1507816b31a7802384135',
    messagingSenderId: '938443124208',
    projectId: 'fir-try-cff76',
    storageBucket: 'fir-try-cff76.firebasestorage.app',
    iosBundleId: 'com.example.currencyConverter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRmts0YwOhWdWEvTBkMiURXMcy_dRA8Wg',
    appId: '1:938443124208:ios:a1507816b31a7802384135',
    messagingSenderId: '938443124208',
    projectId: 'fir-try-cff76',
    storageBucket: 'fir-try-cff76.firebasestorage.app',
    iosBundleId: 'com.example.currencyConverter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAldpQdfiRdY8sdoTTD02uw-m974xFzfrk',
    appId: '1:938443124208:web:0542d6f96d1bba0e384135',
    messagingSenderId: '938443124208',
    projectId: 'fir-try-cff76',
    authDomain: 'fir-try-cff76.firebaseapp.com',
    storageBucket: 'fir-try-cff76.firebasestorage.app',
  );
}
